---
logging:
  level: WARN
  loggers:
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
server:
  adminConnectors:
    -
      port: 7003
      type: http
  applicationConnectors:
    -
      port: 7002
      type: http
  rootPath: /
