server:
  rootPath: /
  applicationConnectors:
    - type: http
      port: 7002
  adminConnectors:
    - type: http
      port: 7003

logging:
  level: WARN
  loggers:
    "io.dropwizard": INFO
    "org.eclipse.jetty": INFO